services:
  
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nvlaskalin
      POSTGRES_PASSWORD: nikola
      POSTGRES_DB: pydatabase
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nvlaskalin -d pydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-application:
    image: python_app
    container_name: python-application
    environment:
      DATABASE_HOSTNAME: db 
      DATABASE_NAME: pydatabase
      DATABASE_PORT: 5432
      DATABASE_USERNAME: nvlaskalin
      DATABASE_PASSWORD: nikola
      SECRET_KEY: j9dWpR53dxAM33ewDh4J4wFCMi52jY5BzXUlrFa5W/4
      ALGORITHM: HS256
    command: bash -c "alembic upgrade head && gunicorn app.main:app -w 3 -b 0.0.0.0:8090 -k uvicorn.workers.UvicornWorker"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx-python
    ports:
      - 8099:8099
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
