services:
  
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres-database
    environment:
      POSTGRES_USER: /run/secrets/db_username 
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: pydatabase
      PGPORT: 5433
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    secrets:
      - db_password
      - db_username

  python-application:
    image: python_app
    container_name: python-application
    environment:
      DATABASE_HOSTNAME: db 
      DATABASE_NAME: pydatabase
      DATABASE_PORT: "5433"
      DATABASE_USERNAME: /run/secrets/db_username
      DATABASE_PASSWORD: /run/secrets/db_password
      SECRET_KEY: j9dWpR53dxAM33ewDh4J4wFCMi52jY5BzXUlrFa5W/4
      ALGORITHM: HS256
    command: bash -c "alembic upgrade head && gunicorn app.main:app -w 3 -b 0.0.0.0:8090 -k uvicorn.workers.UvicornWorker"
    secrets:
      - db_password
      - db_username
    depends_on:
      - db

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx-python
    ports:
      - 8099:8099
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

secrets:
  db_password:
    file: ./db_password.txt
  db_username: 
    file: ./db_username.txt
  db_port:
    file: ./db_port.txt
