name: Internship python application

on:
  push:
    branches:
    - git-actions

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      postgres-database:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: git-actions
          token: ${{ secrets.PAT }} 
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update database
        run: alembic upgrade head
        env: 
          DATABASE_HOSTNAME: postgres-database
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PORT: 5432
          DATABASE_USERNAME: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          
      - name: Test with pytest
        run: |
          pytest tests/


  docker:
    runs-on: testing 
    needs: runner-job 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: git-actions
          token: ${{ secrets.PAT }} 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: grtalca/python-app:latest
    