name: Internship python application
on:
  push:
    branches:
    - git-actions
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres-database:
        image: postgres
        env:
          POSTGRES_PASSWORD: nikola 
          POSTGRES_USER: nvlaskalin
          POSTGRES_DB: pydatabase
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env: 
      DATABASE_HOSTNAME: localhost 
      DATABASE_NAME: pydatabase
      DATABASE_PORT: 5432
      DATABASE_USERNAME: nvlaskalin
      DATABASE_PASSWORD: nikola
      SECRET_KEY: j9dWpR53dxAM33ewDh4J4wFCMi52jY5BzXUlrFa5W/4
      ALGORITHM: HS256
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: git-actions
          token: ${{ secrets.PAT }} 
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Update database
        run: alembic upgrade head
      - name: Test with pytest
        run: |
          pytest tests/
  docker:
    runs-on: ubuntu-latest
    needs: testing 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: git-actions
          token: ${{ secrets.PAT }} 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: grtalca/python-app:latest
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Execute docker compose 
      uses: appleboy/ssh-action@v1.1.0
      with:
        private_key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        scripts: ./home/ubuntu/docker-app/script.sh

